# The URL the site will be built for
base_url = "https://openrouters.com"

# The site title and description; used in feeds by default.
title = "Open Routers"
description = "Dive into our comprehensive guide on the best open source routers available in the market. Find reviews, comparisons, and insights to help you make the right choice!"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = false

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
	{name = "tags"}, # you can have taxonomies with the same name in multiple languages
	{name = "categories", paginate_by = 5},  # 5 items per page for a term
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
#
[extra]
# Put all your custom variables here
# author = "Aaran Xu"
# github = "https://github.com/aaranxu"
# twitter = "https://twitter.com/aaranxu"
# email = "aaranxu@outlook.com"

# If running on netlify.app site, set to true
is_netlify = false

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "Ultimate Guide to Open Source routers"

# Meta keywords
keywords = "open routers, open source routers, open source router review, router os comparisons, best open source routers, open source network solutions, network devices, high performance routers, secure routers, user friendly Routers, openwrt, pfsense, opnsense"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "America/New_York"

## Open Graph + Twitter Cards
[extra.open]
enable = true
# this image will be used as fallback if a page has no image of its own
image = "doks.png"
twitter_site = ""
twitter_creator = ""
facebook_author = ""
facebook_publisher = ""
og_locale = "en_US"

## JSON-LD
[extra.schema]
type = "Organization"
logo = "logo-doks.png"
twitter = "https://twitter.com/aaranxu"
linked_in = ""
github = "https://github.com/aaranxu"
section = "blog" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = false

# Menu items
[[extra.menu.main]]
name = "News"
section = "news"
url = "/news/"
weight = 10

[[extra.menu.main]]
name = "Docs"
section = "docs"
url = "/docs/"
weight = 20

[[extra.menu.main]]
name = "About"
section = "about"
url = "/about"
weight = 30

# [[extra.menu.social]]
# name = "Twitter"
# pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>'
# url = "https://twitter.com/openrouters"
# weight = 10

# [[extra.menu.social]]
# name = "GitHub"
# pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
# url = "https://github.com/openrouters/openwrt"
# post = "v0.1.0"
# weight = 20

# Footer contents
[extra.footer]
info = 'Copyright © 2023 <a href="https://openrouters.com/">openrouters.com</a>'